modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="CLIENT"
mandatory=true

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
mandatory=true

[[dependencies.${mod_id}]]
modId="architectury"
type="required"
versionRange="[13.0,)"
ordering="AFTER"
side="CLIENT"
mandatory=true

[[dependencies.${mod_id}]]
modId="sodium"
type="optional"
versionRange="[0.8.12,)"
ordering="AFTER"
side="CLIENT"
mandatory=false

[[dependencies.${mod_id}]]
modId="reeses_sodium_options"
type="optional"
versionRange="[1.8.3,)"
ordering="AFTER"
side="CLIENT"
mandatory=false

[modproperties.${mod_id}]
"sodium:config_api_user"="restudio.reglassneo.client.integration.ReGlassSodiumConfigEntryPoint"

[[mixins]]
config="reglassneo.mixins.json"
